#!/usr/bin/env python3
"""Compute WCAG contrast ratios for every text/background pair the app uses, and
write verification/contrast.md. Exits non-zero if any pair is below AA (4.5:1).

The colours are read out of the asset catalogue, so this measures what the app
actually ships rather than what a document claims it ships.
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CATALOGUE = os.path.join(ROOT, "GreenCordHandbook", "Assets.xcassets")
AA = 4.5


def read_colorset(name):
    """Return {"light": (r,g,b), "dark": (r,g,b)} from a .colorset."""
    path = os.path.join(CATALOGUE, f"{name}.colorset", "Contents.json")
    data = json.load(open(path))
    out = {}
    for entry in data["colors"]:
        components = entry["color"]["components"]
        rgb = tuple(
            int(components[channel], 16) for channel in ("red", "green", "blue")
        )
        appearances = entry.get("appearances", [])
        is_dark = any(a.get("value") == "dark" for a in appearances)
        out["dark" if is_dark else "light"] = rgb
    return out


def hexify(rgb):
    return "#" + "".join(f"{c:02X}" for c in rgb)


def relative_luminance(rgb):
    def channel(value):
        srgb = value / 255
        return srgb / 12.92 if srgb <= 0.04045 else ((srgb + 0.055) / 1.055) ** 2.4

    r, g, b = (channel(c) for c in rgb)
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast(foreground, background):
    lighter = max(relative_luminance(foreground), relative_luminance(background))
    darker = min(relative_luminance(foreground), relative_luminance(background))
    return (lighter + 0.05) / (darker + 0.05)


WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
# The label colour iOS actually uses, rather than pure black/white.
LABEL_LIGHT = (0, 0, 0)
LABEL_DARK = (255, 255, 255)


def main():
    maroon = read_colorset("BrandMaroon")
    surface = read_colorset("BrandMaroonSurface")
    green = read_colorset("CordGreen")
    page = read_colorset("PageBackground")
    card = read_colorset("CardBackground")
    silver = read_colorset("BrandSilver")

    checks = []

    def check(mode, description, foreground, background, role):
        ratio = contrast(foreground, background)
        checks.append(
            {
                "mode": mode,
                "description": description,
                "fg": hexify(foreground),
                "bg": hexify(background),
                "ratio": ratio,
                "role": role,
                "pass": ratio >= AA,
            }
        )

    for mode in ("light", "dark"):
        label = LABEL_LIGHT if mode == "light" else LABEL_DARK
        check(mode, "Body text on the page background", label, page[mode], "body")
        check(mode, "Body text on a card", label, card[mode], "body")
        check(mode, "Brand maroon text on the page background", maroon[mode], page[mode], "body")
        check(mode, "Brand maroon text on a card", maroon[mode], card[mode], "body")
        check(mode, "Cord green text on a card", green[mode], card[mode], "body")
        check(
            mode,
            "White button text on the maroon surface",
            WHITE,
            surface[mode],
            "button",
        )

    # Silver is chrome - dividers and muted rules - never text, so it is measured
    # and reported but is not held to the text threshold.
    informational = []
    for mode in ("light", "dark"):
        informational.append(
            {
                "mode": mode,
                "description": "Brand silver on a card (dividers and rules, never text)",
                "fg": hexify(silver[mode]),
                "bg": hexify(card[mode]),
                "ratio": contrast(silver[mode], card[mode]),
            }
        )

    failures = [c for c in checks if not c["pass"]]

    lines = [
        "# Contrast",
        "",
        "Every pair of colours the app puts text on, measured against WCAG 2.1",
        f"contrast ratio AA for normal text ({AA}:1).",
        "",
        "Generated by `tools/check_contrast.py`, which reads the values straight out",
        "of `GreenCordHandbook/Assets.xcassets`. Re-run it after any colour change.",
        "",
        "## Source of the brand colours",
        "",
        "`#5A1115` and `#BEBFC1` are the `--primary-color` and `--secondary-color`",
        "declared by the Princeton HS site's own stylesheet - see",
        "`content/source-of-truth.md`.",
        "",
        "## Results",
        "",
        "| Mode | Pair | Foreground | Background | Ratio | AA (4.5:1) |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for item in checks:
        verdict = "PASS" if item["pass"] else "**FAIL**"
        lines.append(
            f"| {item['mode']} | {item['description']} | `{item['fg']}` | "
            f"`{item['bg']}` | {item['ratio']:.2f}:1 | {verdict} |"
        )

    lines += [
        "",
        "## Measured but not held to the text threshold",
        "",
        "| Mode | Pair | Foreground | Background | Ratio |",
        "| --- | --- | --- | --- | --- |",
    ]
    for item in informational:
        lines.append(
            f"| {item['mode']} | {item['description']} | `{item['fg']}` | "
            f"`{item['bg']}` | {item['ratio']:.2f}:1 |"
        )

    lines += [
        "",
        "## Why there are two maroons",
        "",
        f"The official maroon `{hexify(maroon['light'])}` is very dark. On white it is",
        "excellent, but as *text* on a dark background it would be close to invisible.",
        "So the asset catalogue carries two values under one token:",
        "",
        f"* `BrandMaroon` - `{hexify(maroon['light'])}` in light mode, "
        f"`{hexify(maroon['dark'])}` in dark mode. Used for maroon **text**.",
        f"* `BrandMaroonSurface` - `{hexify(surface['light'])}` light, "
        f"`{hexify(surface['dark'])}` dark. The **fill behind white text**, which stays",
        "  dark in both modes so white text on it always passes.",
        "",
        "Views refer only to the token, so nothing in the UI has to know which mode it",
        "is in.",
        "",
    ]
    lines.append(
        f"**Result: {len(checks) - len(failures)} of {len(checks)} text pairs meet AA.**"
        if failures
        else f"**Result: all {len(checks)} text pairs meet AA.**"
    )
    lines.append("")

    os.makedirs(os.path.join(ROOT, "verification"), exist_ok=True)
    with open(os.path.join(ROOT, "verification", "contrast.md"), "w") as fh:
        fh.write("\n".join(lines))

    for item in checks:
        status = "PASS" if item["pass"] else "FAIL"
        print(
            f"  {status}  {item['mode']:<5} {item['ratio']:6.2f}:1  "
            f"{item['description']}"
        )
    print()
    if failures:
        print(f"{len(failures)} pair(s) below AA:")
        for item in failures:
            print(f"  {item['mode']} {item['description']}: {item['ratio']:.2f}:1")
        return 1
    print(f"All {len(checks)} text pairs meet WCAG AA ({AA}:1).")
    print("wrote verification/contrast.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
